-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 23:48:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbfinal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbfinal` ;

-- -----------------------------------------------------
-- Schema dbfinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfinal` ;
USE `dbfinal` ;

-- -----------------------------------------------------
-- Table `dbfinal`.`profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbfinal`.`profesores` ;

CREATE TABLE IF NOT EXISTS `dbfinal`.`profesores` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `legajo` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfinal`.`asignaturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbfinal`.`asignaturas` ;

CREATE TABLE IF NOT EXISTS `dbfinal`.`asignaturas` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `profesores_id_profesor` INT NULL,
  PRIMARY KEY (`id_asignatura`),
  INDEX `fk_asignaturas_profesores_idx` (`profesores_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_asignaturas_profesores`
    FOREIGN KEY (`profesores_id_profesor`)
    REFERENCES `dbfinal`.`profesores` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dbfinal`.`profesores`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbfinal`;
INSERT INTO `dbfinal`.`profesores` (`id_profesor`, `legajo`, `nombres`, `apellidos`, `telefono`) VALUES (1, 001, 'angel', 'garay', '11111111');
INSERT INTO `dbfinal`.`profesores` (`id_profesor`, `legajo`, `nombres`, `apellidos`, `telefono`) VALUES (2, 002, 'paula', 'donofrio', '22222222');
INSERT INTO `dbfinal`.`profesores` (`id_profesor`, `legajo`, `nombres`, `apellidos`, `telefono`) VALUES (3, 003, 'nancy', 'leiva', '33333333');
INSERT INTO `dbfinal`.`profesores` (`id_profesor`, `legajo`, `nombres`, `apellidos`, `telefono`) VALUES (4, 004, 'angelica', 'gutierrez', '44444444');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbfinal`.`asignaturas`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbfinal`;
INSERT INTO `dbfinal`.`asignaturas` (`id_asignatura`, `nombre`, `profesores_id_profesor`) VALUES (1, 'quimica', 1);
INSERT INTO `dbfinal`.`asignaturas` (`id_asignatura`, `nombre`, `profesores_id_profesor`) VALUES (2, 'fisica', 2);
INSERT INTO `dbfinal`.`asignaturas` (`id_asignatura`, `nombre`, `profesores_id_profesor`) VALUES (3, 'logica', 3);
INSERT INTO `dbfinal`.`asignaturas` (`id_asignatura`, `nombre`, `profesores_id_profesor`) VALUES (4, 'civica', 4);
INSERT INTO `dbfinal`.`asignaturas` (`id_asignatura`, `nombre`, `profesores_id_profesor`) VALUES (5, 'programacion', 1);
INSERT INTO `dbfinal`.`asignaturas` (`id_asignatura`, `nombre`, `profesores_id_profesor`) VALUES (6, 'derecho', 1);

COMMIT;

